Repository GeoStat-Framework/PyKrige, pull requests merged in 2022-08, with the labels that each got.

#237 Removed pinv2 references for bug fix
  pykrige/core.py
  pykrige/ok.py
  pykrige/ok3d.py
  pykrige/uk.py
  pykrige/uk3d.py
  tests/test_core.py
Labels: bug

#242 Build: update setuptools config, package structure and CI
  .github/workflows/main.yml
  .gitignore
  LICENSE
  MANIFEST.in
  benchmarks/kriging_benchmarks.py
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/sphinxext/github_link.py
  examples/00_ordinary.py
  examples/01_universal.py
  examples/02_kriging3D.py
  examples/03_gstools_covmodel.py
  examples/04_krige_geometric.py
  examples/05_kriging_1D.py
  examples/06_exact_values_example_1D.py
  examples/07_regression_kriging2d.py
  examples/08_krige_cv.py
  examples/10_classification_kriging2d.py
  pyproject.toml
  setup.cfg
  setup.py
  src/pykrige/__init__.py
  src/pykrige/ck.py
  src/pykrige/compat.py
  src/pykrige/core.py
  src/pykrige/kriging_tools.py
  src/pykrige/lib/__init__.py
  src/pykrige/lib/cok.pyx
  src/pykrige/lib/variogram_models.pxd
  src/pykrige/lib/variogram_models.pyx
  src/pykrige/ok.py
  src/pykrige/ok3d.py
  src/pykrige/rk.py
  src/pykrige/uk.py
  src/pykrige/uk3d.py
  src/pykrige/variogram_models.py
  tests/test_api.py
  tests/test_classification_krige.py
  tests/test_core.py
  tests/test_regression_krige.py
Labels: packaging, Refactoring, CI/CD

#247 uk: fix external_Z_array bug
  src/pykrige/uk.py
Labels: bug

#245 GSTools: support latlon models for geographic coordinates
  pyproject.toml
  src/pykrige/compat_gstools.py
  src/pykrige/ok.py
  src/pykrige/ok3d.py
  src/pykrige/uk.py
  src/pykrige/uk3d.py
Labels: bug, enhancement, new feature, solved upstream

#252 Prepare v1.7
  CHANGELOG.md
  docs/source/_templates/autosummary/class.rst
  pyproject.toml
Labels: docs
